### PR TITLE
Host templates: Remove incorrect statements

### PR DESCRIPTION
**Pull request by srisankethu**
Fixes https://github.com/fedora-infra/mirrormanager2/issues/145

### CODE REVIEW

**Comment by pypingou** [comment]
@adrianreber, looks good to me, and to you?

**Comment by adrianreber** [comment]
I probably did not describe my intentions in the issue good enough.

The goal was to remove the complete "Master rsync server Access Control List IPs" section.

I would also make it configurable if the MirrorManager installation has this feature or not. So it should be configurable. Other projects (which might be interested in using MirrorManager) might use this functionality. For Fedora's setup, with its tiering, it just does not make much sense.

**Comment by srisankethu** [comment]
@adrianreber I am a beginner...Can you tell me what changes can i makes in these files?

**Comment by ralphbean** [comment]
Hm, I'm going to close this one since it seems like it doesn't match up with @adrianreber's ideas in #163.

@srisankethu thanks for submitting it!  Can you follow up in #163 and ask for more details there about what should be fixed?

**Comment by ralphbean** [comment]
Sorry.. I meant #145, there.

**Comment by srisankethu** [comment]
@adrianreber :+1:

**Pull request closed without merging**
