### PR TITLE
Change the way the FPCA is checked

### PR DESCRIPTION
**Pull request by pypingou**
Signed-off-by: Pierre-Yves Chibon <pingou@pingoured.fr>

### CODE REVIEW

**Comment by adrianreber** [comment]
All the admin tests are failing. I had a look at it, but I do not understand why it fails. Do you have any idea why the admin ui tests are failing?

**Comment by adrianreber** [comment]
Okay, already figured it out.

**Comment by pypingou** [comment]
We're missing 'signed_fpca' in our mocked user?

**Comment by adrianreber** [comment]
> We're missing 'signed_fpca' in our mocked user?

I can fix that. Now there is one more test error I need to figure out before merging this.

**Pull request merged**
