### PR TITLE
Create noauthed master for mirror publiclist

### PR DESCRIPTION
**Pull request by puiterwijk**
This makes it possible to make publiclist varnish cached
because that doesn't depend on any cookie status anymore.

Signed-off-by: Patrick Uiterwijk <puiterwijk@redhat.com>

### CODE REVIEW

**Comment by adrianreber** [comment]
I cannot say if it is correct but I like the idea very much to be able to cache the mirrorlist as the content does not change that often.

**Comment by pypingou** [comment]
Does not compile:
````
mirrormanager2/mirrormanager2/templates/fedora/master.html", line 3, in template
    {% block nav %}
TemplateSyntaxError: unexpected '%'
````

**Comment by puiterwijk** [comment]
The compile error is now fixed :)

**Comment by pypingou** [comment]
Cool, testing it looks good to me! :)

**Comment by pypingou** [comment]
This way, we can cache everything but the front page (and the pages needing auth), nice and easy! :)

**Comment by puiterwijk** [comment]
Thanks, this should improve it a lot!

**Pull request merged**
