### PR TITLE
Defer loading of host.config

### PR DESCRIPTION
**Pull request by adrianreber**
The field host.config is never used but increases the required memory dramatically for certain database operation. Its loading is now deferred and as it is never read the call write the data has also been removed.

### CODE REVIEW

**Comment by adrianreber** [comment]
The MM1 code also does not store the config anywhere. So this change in behaviour has somehow crept into MM2. This is probably a database field which could be removed. Never read, never written.

**Comment by puiterwijk** [comment]
Looks sane to me. :+1:

**Comment by pypingou** [comment]
:+1: for me as well

**Comment by adrianreber** [comment]
Thanks!

**Pull request merged**
