### PR TITLE
First pass at update-single-file-detail

### PR DESCRIPTION
**Pull request by ralphbean**
This is a script we might try and use to speed up recovery of the pkl data.

### CODE REVIEW

**Comment by adrianreber** [comment]
Would it make sense to integrate this functionality directly into umdl?

**Comment by ralphbean** [comment]
> Would it make sense to integrate this functionality directly into umdl?

I tried that first.  It seems like you would only need to replace that ``os.walk`` statement with a fake list including only your filename, but:

- What if you pass it a file that is not one of the ones returned by ``short_filelist``.. I'm not sure how that would work and..
- The logic in ``sync_categories_directories`` confused me when I was trying to modify it for this, so I reversed course and split it out into its own script.

If there are ways to deal with those two things, then yes we could include it in umdl.  :)

**Comment by ralphbean** [comment]
@adrianreber, @pypingou any further feedback here.  If this isn't something we want to merge, we can always :-1: and close it to get it out of the queue.

**Comment by pypingou** [comment]
I'm :+1: to merge and we can always kick it out if we end-up merging it into the UMDL later.

**Comment by adrianreber** [comment]
:+1: what @pypingou said

**Comment by ralphbean** [comment]
Thanks guys!

**Pull request merged**
