### PR TITLE
Unit-Tests for the flask application and some of the scripts

### PR DESCRIPTION
**Pull request by pypingou**

### CODE REVIEW

**Comment by ralphbean** [comment]
@oddshocks, can you have a look at reviewing this?

**Comment by oddshocks** [comment]
Woah, totally missed this notification. Sorry! Checking it out now.

...

Looks good to me! Two small things I noticed that might be tweaked:
- typo: 3 instances of the words "before every tests" should be "before every test"
- camel case variables and strings around https://github.com/fedora-infra/mirrormanager2/pull/14/files#diff-72deec2152f55f375f1e2a5cec5c526aL26 and below (not a big deal since unittest uses it everywhere)

**Comment by pypingou** [comment]
@oddshocks I adjusted the PR as you suggested

**Comment by oddshocks** [comment]
I don't see any problem with merging this in, if you're good and ready. :+1:

**Comment by pypingou** [comment]
Let's do it then :)

**Pull request merged**
