### PR TITLE
Remove <0.80 requirement on IPy

### PR DESCRIPTION
**Pull request by puiterwijk**
Signed-off-by: Patrick Uiterwijk puiterwijk@redhat.com

### CODE REVIEW

**Comment by pypingou** [comment]
Because the issue is fixed?

**Comment by puiterwijk** [comment]
Because I have not been able to see any reason why it was added (requirements.txt doesn't list the version requirement, so pip would happily install the latest) and this has not been changed since its introduction two years ago in the spec file.

**Comment by pypingou** [comment]
In theory I have nothing against, but I'd rather finding back why this was added before actually merging this PR.

**Comment by bowlofeggs** [comment]
The IPy 0.80 release notes don't say anything that sounds scary to me:

https://github.com/autocracy/python-ipy/blob/master/ChangeLog

I'm comfortable with dropping the requirement, given the release notes. I agree with @pypingou that it would be helpful to know why that requirement was put in place, but it's also possible that that information has been lost.

**Comment by adrianreber** [comment]
I cannot load the pkl on Fedora with python-IPy-0.81-16.fc25.noarch:

TypeError: ('__init__() takes at least 2 arguments (1 given)', <class 'IPy.IP'>, ())

Same code works on CentOS7 with python-IPy-0.75-6.el7.noarch

Not really sure where this comes from.

**Comment by pypingou** [comment]
It is my understanding that this has now been done on the servers of the Fedora Infra, and afaict it all works.

So I guess I should lift my suspicions and say 👍 to this PR :)

**Comment by adrianreber** [comment]
The main problem seems to be that it is not possible to mix versions. A pkl generated with an older version does not work in a newer version. But yes, let's merge this.

**Pull request merged**
