### PR TITLE
Fix link to the crawler log file

### PR DESCRIPTION
**Pull request by adrianreber**
Simple fix to link to the correct crawler log file.

### CODE REVIEW

**Comment by ralphbean** [comment]
Sure.  :+1: here.

Although, there if often a better way to use ``url_for(...)`` by passing some arguments in.  That may not work in this case.  Do you know what I mean @adrianreber?

**Comment by adrianreber** [comment]
@ralphbean I was looking for a way to get the base URL of the application. This seemed like one way to get it, but if there is better way to retrieve the base URL I would be happy to learn about it.

**Comment by ralphbean** [comment]
> if there is better way to retrieve the base URL

No, this is the best way to retrieve the base url.  However, you can use ``url_for`` to retrieve *specific* urls that are provided by the flask application.  I see now that the crawler host logs, however, are not served by the flask application and would instead be served by apache, so my suggestion is not relevant here.

:+1: to merge.

**Comment by pypingou** [comment]
:+1: as well

**Pull request merged**
