### PR TITLE
Adjust repomap for the new repo layout

### PR DESCRIPTION
**Pull request by pypingou**
Patch from Dennis Gilmore

### CODE REVIEW

**Comment by pypingou** [comment]
Apparently this fixes https://github.com/fedora-infra/mirrormanager2/issues/161

**Comment by ralphbean** [comment]
:+1: here

**Comment by pypingou** [comment]
Apparently it doesn't actually fix the problem entirely but this change is good nonetheless so let's merge

**Comment by ralphbean** [comment]
Cool, cool.

**Pull request merged**
