### PR TITLE
repomap: modular changes for Fedora 28

### PR DESCRIPTION
**Pull request by adrianreber**
This is based on Dennis' PR #237 to support the new location of the
'modular' content. This moves the original code a bit around to work
correctly. This has been tested in staging and repositories have been
created correctly:

```
         prefix
------------------------
 rawhide-modular
 rawhide-modular
 rawhide-modular
 rawhide-modular-source
 rawhide-modular-debug
 rawhide-modular-debug
 rawhide-modular-debug
```

Additional, now unnecessary, 'modular' handling code has been removed
from umdl.

Signed-off-by: Adrian Reber <adrian@lisas.de>

### CODE REVIEW

**Comment by adrianreber** [comment]
@ausil I had to move one of the if branches a bit around but now it works. Once this is merged I can make a new release and we can get this on the production systems.

**Comment by pypingou** [comment]
Looks fine to me, I'll let Dennis comment as well if he wishes to

**Comment by pypingou** [comment]
Wrong button :(

**Comment by ausil** [comment]
it doe not look like it covers the case where updates and updates-testing has a Everything repo. that is not yet on disk

**Comment by adrianreber** [comment]
In staging the updates repository are now correctly detected for Modular and Everything

**Comment by ausil** [comment]
@adrianreber if you are happy this meets the needs I am good with it.

**Pull request merged**
